FROM ubuntu:focal

ENV TZ=Asia/Ho_Chi_Minh
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt update && \
    apt upgrade && \
    apt install -y git && \
    git clone https://github.com/nVietUK/nVietUK.git && \
    cd nVietUK/ && \
    chmod +x .sh/install-tensorflow.sh && \
    chmod +x .sh/install-tensorRT.sh && \
    chmod +x .sh/install-python.sh
RUN cd nVietUK/ && .sh/install-tensorflow.sh -f