FROM ubuntu:focal

RUN apt update && \
    apt upgrade && \
    apt install -y git && \
    git clone https://github.com/nVietUK/nVietUK.git && \
    cd nVietUK/ && \
    chmod +x .sh/install-tensorflow.sh && \
    chmod +x .sh/install-tensorRT.sh && \
    chmod +x .sh/install-python.sh && \
    .sh/install-tensorflow.sh